services:
  - type: web
    name: travel-guruji-sih
    runtime: node
    plan: free
    region: oregon
    buildCommand: npm install && npm --prefix backend install && npm run build
    startCommand: node backend/server.js
    envVars:
      - key: NODE_VERSION
        value: 20.18.0
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        value: mongodb+srv://apcfriend123_db_user:Sounava2005@travelguruji.2lvhyea.mongodb.net/?appName=TravelGuruji
      - key: JWT_SECRET
        value: travel_guruji_secret_2026
